spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quicknotes
    username: postgres
    driver-class-name: org.postgresql.Driver
    password: 8763
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true
        ddl-auto: = update
