spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    driver-class-name: org.postgresql.Driver
    password: ${DB_PASSWORD}
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    properties:
      hibernate:
        auto_quote_keyword: true

key:
  access: zgXveUgNrHX8CvnClpJLyvnE3gx7IHqz38TxxPb8s3Y=
  refresh: 4vhupBx1DbjoxwemKKeAZuZIFYr22aLfEF1J/1tntg8=

messages:
  hello: Hello from Digital Ocean!